### ISSUE TITLE
Whitelist Files

### ISSUE THREAD

**Issue by beucismis** [TechWiz-3/linksafe#3]
Hi friend, I added a new file to my repository. I have whitelist ([linkcheck.yml](https://github.com/beucismis/awesome-fetch/blob/main/.github/workflows/linkcheck.yml#L12)) this file. But it didn't work.

https://github.com/beucismis/awesome-fetch/actions/runs/3096274082/jobs/5011636944

**Comment by TechWiz-3** [comment]
Hey man, thanks for opening this issue.

I think I know what the issue in my code is, I'm testing right now and will get back to you as soon as possible 👍

**Comment by TechWiz-3** [comment]
I have fixed the problem, it should work with no problems now. Thanks a lot for bringing this bug to my attention, it allowed me to improve my code a lot 🙏 

In case you're curious, the issue was that the files without a `./` before them were not being recognised as the function that gets the file paths always returns with a relative path. I fixed this by adding a `./` to the start of whitelist files and directories that don't already have it 👍

**Comment by beucismis** [comment]
It's work. Thanks. Good luck...

**Comment by TechWiz-3** [comment]
You too brother 💪

**Comment by TechWiz-3** [comment]
And thanks for the star :)
